[package]
name = "ircx-net"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ircx-proto.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
rustls.workspace = true
rustls-pki-types.workspace = true
webpki-roots.workspace = true
tracing.workspace = true
